# Anorvis Multi-Agent System Configuration
# This configuration defines the main orchestrator and specialized agents

llms:
  anorvis_llm:
    _type: ollama
    model_name: mistral:latest
    base_url: http://localhost:11434
    temperature: 0.1
    max_tokens: 1000
    timeout: 120

functions:
  # Main orchestrator agent
  anorvis:
    _type: anorvis
    llm_name: anorvis_llm
    backrub: backrub
    warren: warren
    system_prompt: |
      You are Anorvis, an intelligent AI assistant that coordinates specialized agents.
      You analyze user requests and route them to the appropriate specialist agent.
      You only handle general queries and time/date requests directly when no specialist agent is available.
      
      Available agents:
      - Backrub: Research and information gathering
      - Warren: Financial analysis and advice
      
      Always route to the most appropriate specialist agent when possible.

  # Research agent with search tools
  backrub:
    _type: tool_calling_agent
    llm_name: anorvis_llm
    tool_names: [internet_search, wikipedia_search]
    system_prompt: |
      You are Backrub, a specialized research agent. You excel at finding information, 
      conducting research, and gathering data. Always provide thorough, well-researched responses.
      Use the available search tools to find the most current and accurate information.
    verbose: true
    handle_tool_errors: true

  # Finance agent  
  warren:
    _type: warren
    llm_name: anorvis_llm
    system_prompt: |
      You are Warren, a specialized finance agent. You excel at financial analysis, 
      budgeting, investments, and financial planning. Always provide professional, 
      actionable financial advice.

  # Foundational tools that all agents can use
  current_datetime:
    _type: current_datetime

  # Web search tools (only used by Backrub)
  internet_search:
    _type: tavily_internet_search
    max_results: 5

  wikipedia_search:
    _type: wiki_search
    max_results: 3

workflow:
  _type: tool_calling_agent
  llm_name: anorvis_llm
  tool_names: [anorvis]
  verbose: true
  handle_tool_errors: true
  max_iterations: 5 